version: "3.9"
services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: todo_dev_db
      POSTGRES_PASSWORD: todo_dev_db
      POSTGRES_DB: todo_dev_db
    ports:
      - "5432:5432"
    volumes:
      - .:/usr/postgres_database